FROM node:20-alpine AS builder
ENV CI=true
WORKDIR /app

COPY . .

RUN npm install -g pnpm
RUN pnpm install
RUN pnpm nx build @yellows/web

FROM node:20-alpine
WORKDIR /app

COPY --from=builder /app/dist/apps/web .

EXPOSE 3000
CMD ["node", "server.js"]
