# syntax=docker/dockerfile:1.7
FROM node:20-alpine AS base
RUN corepack enable
WORKDIR /app

FROM base AS deps
COPY package.json pnpm-workspace.yaml ./
COPY apps/api/package.json apps/api/package.json
COPY libs/contract/package.json libs/contract/package.json
COPY libs/config/package.json libs/config/package.json
RUN pnpm install --frozen-lockfile=false

FROM deps AS build
COPY . .
RUN pnpm nx run @yellows/api:build

FROM node:20-alpine AS runner
RUN corepack enable
WORKDIR /app
ENV NODE_ENV=production
ENV PORT=3333

COPY --from=build /app/package.json .
COPY --from=build /app/pnpm-workspace.yaml .
COPY --from=build /app/apps/api/package.json apps/api/package.json
COPY --from=build /app/libs/contract/package.json libs/contract/package.json
COPY --from=build /app/libs/config/package.json libs/config/package.json

RUN pnpm install --prod --frozen-lockfile=false

COPY --from=build /app/apps/api/dist ./apps/api/dist
COPY --from=build /app/libs/contract/dist ./libs/contract/dist
COPY --from=build /app/libs/config/dist ./libs/config/dist
COPY --from=build /app/apps/api/src/assets ./apps/api/src/assets

EXPOSE 3333
CMD ["node", "apps/api/dist/main.js"]
